version: "3"
services:
 mongodb:
  image: "mongo"
  ports:
  - "27017:27017"
 backend:
  build: ./docker-backend/
  ports:
  - "4000:4000"
  volumes: 
   - ./docker-backend:/usr/src/app
  depends_on:
   - mongodb
 frontend:
  build: ./docker-frontend/
  ports:
   - "3000:3000"
  volumes:
   - ./docker-frontend:/usr/src/app
  depends_on:
   - backend
  stdin_open: true
  tty: true